version: "3"

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test1
      - POSTGRES_USER=moni
      - POSTGRES_PASSWORD=moni

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
